name: 'Rocking Test JS Action'
description: 'This test action will fully rock the ice castle world.'
author: 'Pedestrians International Ice Castles'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Run Time'
    required: true
    default: '500'

# Define your outputs here.
outputs:
  time:
    description: 'Chainsaw time'
    run: echo "${{ outputs.time.description }}"

runs:
  using: node20
  main: dist/index.js
